
"""init

Revision ID: 6f0d8b1a18af
Revises: 
Create Date: 2025-12-24 01:10:37.170256

"""
from app.core.types import GeoPoint, GUID
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0d8b1a18af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', GUID(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.String(length=2000), nullable=True),
    sa.Column('created_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('tipo', sa.Enum('PROPIETARIO', 'ARRENDATARIO', 'CORREDOR', 'PROVEEDOR', name='tipo_persona'), nullable=False),
    sa.Column('nombres', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=True),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('giro', sa.String(length=200), nullable=True),
    sa.Column('direccion_contacto', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('propiedades',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('direccion_linea1', sa.Text(), nullable=False),
    sa.Column('comuna', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('latlon', GeoPoint(from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('tipo', sa.Enum('CASA', 'DEPARTAMENTO', 'OFICINA', 'LOCAL', 'TERRENO', name='tipo_propiedad'), nullable=False),
    sa.Column('estado_actual', sa.Enum('ARRENDADA', 'DISPONIBLE', 'VENDIDA', 'EN_VENTA', 'DESOCUPADA', 'MANTENCION', 'LITIGIO', 'INACTIVA', name='estado_propiedad'), nullable=False),
    sa.Column('valor_arriendo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_venta', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index('idx_propiedades_latlon', 'propiedades', ['latlon'], unique=False)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CORREDOR', 'FINANZAS', 'LECTURA', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contratos_arriendo',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('propiedad_id', GUID(), nullable=False),
    sa.Column('arrendatario_id', GUID(), nullable=False),
    sa.Column('propietario_id', GUID(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('renta_mensual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('CLP', 'UF', name='moneda'), nullable=False),
    sa.Column('reajuste_tipo', sa.Enum('UF', 'IPC', 'FIJO', 'NONE', name='reajuste_tipo'), nullable=False),
    sa.Column('reajuste_periodo_meses', sa.Integer(), nullable=True),
    sa.Column('reajuste_factor_inicial', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('dia_pago', sa.Integer(), nullable=True),
    sa.Column('garantia_meses', sa.Integer(), nullable=True),
    sa.Column('comision_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('VIGENTE', 'TERMINADO', 'RESCILIADO', 'FIRMADO', 'BORRADOR', name='estado_contrato'), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['arrendatario_id'], ['personas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['propiedad_id'], ['propiedades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['propietario_id'], ['personas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estados_propiedad_historial',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('propiedad_id', GUID(), nullable=False),
    sa.Column('estado', sa.Enum('ARRENDADA', 'DISPONIBLE', 'VENDIDA', 'EN_VENTA', 'DESOCUPADA', 'MANTENCION', 'LITIGIO', 'INACTIVA', name='estado_propiedad_hist'), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('actor_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['propiedad_id'], ['propiedades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cobranzas',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('contrato_id', GUID(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('monto_original', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_ajustado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PAGADO', 'ATRASADO', 'PARCIAL', 'CONDONADO', name='estado_cobranza'), nullable=False),
    sa.Column('mora_monto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('medio_pago', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos_arriendo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_detalle',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('cobranza_id', GUID(), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('medio_pago', sa.String(length=100), nullable=True),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cobranza_id'], ['cobranzas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos_detalle')
    op.drop_table('cobranzas')
    op.drop_table('estados_propiedad_historial')
    op.drop_table('contratos_arriendo')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_propiedades_latlon', table_name='propiedades')
    op.drop_table('propiedades')
    op.drop_table('personas')
    op.drop_table('documentos')
    # ### end Alembic commands ###
